#PARENT_ID의 정보와 갯수를 빼낸 테이블 생성
SELECT A.ID, IFNULL(B.CNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA A LEFT JOIN
    (SELECT PARENT_ID, COUNT(PARENT_ID) AS CNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID) B
ON A.ID = B.PARENT_ID
ORDER BY A.ID;