SELECT A.PRODUCT_CODE, SUM(B.SALES_AMOUNT) * A.PRICE AS "SALES"
FROM PRODUCT A
JOIN OFFLINE_SALE B
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY B.PRODUCT_ID
ORDER BY SUM(B.SALES_AMOUNT) * A.PRICE DESC, A.PRODUCT_CODE;