SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (
    SELECT A.SALES_DATE, A.PRODUCT_ID, A.USER_ID, A.SALES_AMOUNT
    FROM ONLINE_SALE A
    WHERE A.SALES_DATE BETWEEN TO_DATE('2022-03-01', 'YYYY-MM-DD') AND TO_DATE('2022-03-31', 'YYYY-MM-DD')
    
    UNION ALL
    
    SELECT B.SALES_DATE, B.PRODUCT_ID, NULL AS USER_ID, B.SALES_AMOUNT
    FROM OFFLINE_SALE B
    WHERE B.SALES_DATE BETWEEN TO_DATE('2022-03-01', 'YYYY-MM-DD') AND TO_DATE('2022-03-31', 'YYYY-MM-DD')
)
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;