--음식 종류별, 즐찾 가장 많은 식당
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO R
WHERE FAVORITES = (SELECT MAX(FAVORITES)
                   FROM REST_INFO
                   WHERE FOOD_TYPE = R.FOOD_TYPE)
ORDER BY FOOD_TYPE DESC;