# SELECT ANIMAL_TYPE, COUNT(*) AS "count"
# FROM ANIMAL_INS
# GROUP BY ANIMAL_TYPE;

SELECT ANIMAL_TYPE, COUNT(*) AS COUNT
FROM ANIMAL_INS
WHERE ANIMAL_TYPE IN ('CAT', 'DOG')
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE ASC