-- 2021년 가입, 비율 = (상품 구매 회원 수/ 가입한 전체 회원 수)
SELECT TO_CHAR(C.SALES_DATE, 'YYYY') AS YEAR, TO_NUMBER(TO_CHAR(C.SALES_DATE, 'MM')) AS MONTH, COUNT(DISTINCT C.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT C.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE TO_CHAR(JOINED, 'YYYY') = 2021), 1) PURCHASED_RATIO
FROM (SELECT B.USER_ID, B.SALES_DATE
     FROM USER_INFO A
     JOIN ONLINE_SALE B
     ON A.USER_ID = B.USER_ID
     WHERE TO_CHAR(A.JOINED, 'YYYY') = 2021) C
GROUP BY TO_CHAR(C.SALES_DATE, 'YYYY'), TO_NUMBER(TO_CHAR(C.SALES_DATE, 'MM'))
ORDER BY TO_CHAR(C.SALES_DATE, 'YYYY'), TO_NUMBER(TO_CHAR(C.SALES_DATE, 'MM'));