SELECT FLAVOR
FROM (SELECT FLAVOR, TOTAL_ORDER
     FROM FIRST_HALF
     UNION ALL  #MYSQL은 풀 아우터 조인이 없다 그래서 UNION ALL 사용
     SELECT FLAVOR, TOTAL_ORDER
     FROM JULY) AS TOTAL
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3;