--2022-4-13에 취소되지 않은 / 흉부외과(CS)
SELECT C.APNT_NO, A.PT_NAME, C.PT_NO, C.MCDP_CD, B.DR_NAME, C.APNT_YMD
FROM APPOINTMENT C
JOIN PATIENT A
ON C.PT_NO = A.PT_NO
JOIN DOCTOR B
ON C.MDDR_ID = B.DR_ID
WHERE C.APNT_CNCL_YN = 'N' AND C.MCDP_CD = 'CS' AND TO_CHAR(C.APNT_YMD, 'YYYY-MM-DD') = '2022-04-13'
ORDER BY C.APNT_YMD;