SELECT C.APNT_NO, A.PT_NAME, A.PT_NO, B.MCDP_CD, B.DR_NAME, C.APNT_YMD
FROM APPOINTMENT C
JOIN DOCTOR B
ON B.DR_ID = C.MDDR_ID
JOIN PATIENT A
ON A.PT_NO = C.PT_NO 
WHERE DATE_FORMAT(C.APNT_YMD,'%Y-%m-%d') = '2022-04-13'
AND C.APNT_CNCL_YN = 'N' 
AND B.MCDP_CD = 'CS'
ORDER BY C.APNT_YMD;