SELECT TO_NUMBER(HOUR) AS HOUR, SUM(COUNT) AS COUNT
FROM
(
SELECT TO_CHAR(datetime,'fmHH24') AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS 
GROUP BY TO_CHAR(datetime,'fmHH24')
UNION ALL
SELECT TO_CHAR(LEVEL - 1) AS HOUR, COUNT(*)-1 AS COUNT
FROM DUAL
CONNECT BY LEVEL < 25
GROUP BY LEVEL - 1
)
GROUP BY HOUR
ORDER BY HOUR
;