--총 대여 횟수가 5회 이상인 테이블

SELECT TO_NUMBER(TO_CHAR(START_DATE,'FMMM')) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_NUMBER(TO_CHAR(START_DATE, 'MM')) BETWEEN 8 AND 10
AND CAR_ID IN (SELECT CAR_ID
              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
              WHERE TO_NUMBER(TO_CHAR(START_DATE, 'MM')) BETWEEN 8 AND 10
              GROUP BY CAR_ID
              HAVING COUNT(*) >= 5)
GROUP BY TO_NUMBER(TO_CHAR(START_DATE,'FMMM')), CAR_ID
ORDER BY TO_NUMBER(TO_CHAR(START_DATE,'FMMM')), CAR_ID DESC;