# 대여 시작일 기준 22-8 ~ 22-10까지 총 대여 횟수가 5회 이상 / 월별 자동차 ID별 총 대여 횟수 / 월 오름차순, ID 내림차순
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
AND CAR_ID IN (SELECT CAR_ID
              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
              WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
              GROUP BY CAR_ID
              HAVING COUNT(*) >= 5)
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC;