-- 세단/10월에 대여 시작/중복x
SELECT DISTINCT A.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE = '세단' AND TO_CHAR(B.START_DATE,'MM') = 10
ORDER BY A.CAR_ID DESC;