SELECT CONCAT('/home/grep/src/',B.BOARD_ID,'/',B.FILE_ID,B.FILE_NAME,B.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS A JOIN USED_GOODS_FILE AS B
ON A.BOARD_ID = B.BOARD_ID
WHERE B.BOARD_ID = (SELECT A.BOARD_ID
                   FROM USED_GOODS_BOARD A
                   ORDER BY A.VIEWS DESC
                   LIMIT 1)
ORDER BY B.FILE_ID DESC;
