# 2022년 1월 카테고리별 도서 판매량
SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM BOOK A JOIN BOOK_SALES B
ON A.BOOK_ID = B.BOOK_ID
WHERE DATE_FORMAT(B.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY DATE_FORMAT(B.SALES_DATE, '%Y-%m'), A.CATEGORY
ORDER BY A.CATEGORY;